In [35]:
import numpy as np

In [36]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [39]:
np.array(my_list)

array([1, 2, 3])

In [40]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [43]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [46]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones(3)

array([1., 1., 1.])

In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [55]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [56]:
np.random.rand(2)

array([0.93464712, 0.08436357])

In [58]:
np.random.rand(3,3)

array([[0.67919365, 0.09243611, 0.03018627],
       [0.27743155, 0.10957349, 0.20540973],
       [0.98173732, 0.45015253, 0.17836249]])

In [59]:
np.random.randn(2)

array([ 0.86941745, -0.15344951])

In [60]:
np.random.randn(3,3)

array([[-0.41191465, -0.12580794,  1.82867771],
       [ 0.26262215, -0.67855641, -0.53924464],
       [-0.88975174, -0.79111536,  2.10509245]])

In [61]:
np.random.randint(1,100)

24

In [62]:
np.random.randint(1,100,10)

array([68, 70, 81, 89, 86, 18, 23, 83, 95, 48])

In [68]:
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [64]:
array_1d.shape

(3,)

In [65]:
array_2d.shape

(3, 3)

In [69]:
array_3d.shape

(3, 3, 3)

In [74]:
arr = np.random.randint(1,25,25)
arr

array([12, 16, 22,  5,  7, 10, 11, 11,  1, 13,  7,  3,  5, 16, 20, 11, 19,
       19,  2, 21, 16,  6,  9,  4,  1])

In [75]:
arr.shape

(25,)

In [76]:
arr.reshape(1,25)

array([[12, 16, 22,  5,  7, 10, 11, 11,  1, 13,  7,  3,  5, 16, 20, 11,
        19, 19,  2, 21, 16,  6,  9,  4,  1]])

In [77]:
arr.reshape(1,25).shape

(1, 25)

In [78]:
arr.reshape(5,5)

array([[12, 16, 22,  5,  7],
       [10, 11, 11,  1, 13],
       [ 7,  3,  5, 16, 20],
       [11, 19, 19,  2, 21],
       [16,  6,  9,  4,  1]])

In [79]:
arr.reshape(25,1)

array([[12],
       [16],
       [22],
       [ 5],
       [ 7],
       [10],
       [11],
       [11],
       [ 1],
       [13],
       [ 7],
       [ 3],
       [ 5],
       [16],
       [20],
       [11],
       [19],
       [19],
       [ 2],
       [21],
       [16],
       [ 6],
       [ 9],
       [ 4],
       [ 1]])

In [80]:
arr.reshape(25,1).shape

(25, 1)

In [81]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
array_2d.reshape(-1).shape

(9,)

In [83]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [84]:
array_3d.reshape(-1).shape

(27,)

In [88]:
ranarr = np.random.randint(1,10,10)
ranarr

array([9, 6, 3, 1, 8, 2, 5, 4, 7, 4])

In [89]:
ranarr.max()

9

In [90]:
ranarr.argmax()

0

In [91]:
ranarr.min()

1

In [92]:
ranarr.argmin()

3

In [93]:
arr.dtype

dtype('int32')

In [95]:
arr1=np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [2]:
import numpy as np

In [4]:
x = np.arange(0,6)
x

array([0, 1, 2, 3, 4, 5])

In [9]:
x[5]

5

In [7]:
x[1:4]

array([1, 2, 3])

In [8]:
x[0:6:2]

array([0, 2, 4])

In [10]:
x[0:2]=50
x

array([50, 50,  2,  3,  4,  5])

In [11]:
x = np.arange(0,6)
x

array([0, 1, 2, 3, 4, 5])

In [12]:
y = x[0:6]
y

array([0, 1, 2, 3, 4, 5])

In [13]:
y[:] = 25
y

array([25, 25, 25, 25, 25, 25])

In [14]:
z = y.copy()
z

array([25, 25, 25, 25, 25, 25])

In [15]:
k = np.array (([5,10,15], [20,25,30], [35,40,45]))
k

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
k[0]

array([ 5, 10, 15])

In [22]:
k[0][2]

15

In [21]:
k[0,1]

10

In [23]:
k[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
k[:,2]

array([15, 30, 45])

In [25]:
s = np.arange(0,11)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
[s[0],s[5],s[9]]

[0, 5, 9]

In [27]:
s[[0,8,7]]

array([0, 8, 7])

In [28]:
i = np.array (([5,10,15], [20,25,30], [35,40,45]))
i

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
i[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [30]:
si = np.arange(1,7)
si

array([1, 2, 3, 4, 5, 6])

In [31]:
si > 2

array([False, False,  True,  True,  True,  True])

In [33]:
bool_si = si > 2
bool_si

array([False, False,  True,  True,  True,  True])

In [34]:
si[bool_si]

array([3, 4, 5, 6])

In [35]:
si

array([1, 2, 3, 4, 5, 6])

In [36]:
si[si<4]

array([1, 2, 3])

In [39]:
e = 2
si[si<=2]

array([1, 2])